<?php
/**
 * GetConfigResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Chainpoint Node
 *
 * Documentation for the Chainpoint Node API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@chainpoint.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 1.0.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetConfigResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetConfigResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetConfigResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetConfigResponse"
     */
    public function testGetConfigResponse()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "proof_expire_minutes"
     */
    public function testPropertyProofExpireMinutes()
    {
    }

    /**
     * Test attribute "get_proofs_max_rest"
     */
    public function testPropertyGetProofsMaxRest()
    {
    }

    /**
     * Test attribute "post_hashes_max"
     */
    public function testPropertyPostHashesMax()
    {
    }

    /**
     * Test attribute "post_verify_proofs_max"
     */
    public function testPropertyPostVerifyProofsMax()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "calendar"
     */
    public function testPropertyCalendar()
    {
    }
}
