<?php
/**
 * GetProofsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Chainpoint\Client
 * @author   Chainpoint Codegen team
 * @link     https://github.com/Chainpoint-api/Chainpoint-codegen
 */

/**
 * Chainpoint Node
 *
 * Documentation for the Chainpoint Node API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@chainpoint.org
 * Generated by: https://github.com/Chainpoint-api/Chainpoint-codegen.git
 * Chainpoint Codegen version: 1.0.14
 */

/**
 * NOTE: This class is auto generated by the Chainpoint code generator program.
 * https://github.com/Chainpoint-api/Chainpoint-codegen
 * Please update the test case below to test the model.
 */

namespace Chainpoint\Client;

/**
 * GetProofsResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetProofsResponse
/**
 * @package     Chainpoint\Client
 * @author      Chainpoint Codegen team
 * @link        https://github.com/Chainpoint-api/Chainpoint-codegen
 */
class GetProofsResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetProofsResponse"
     */
    public function testGetProofsResponse()
    {
    }

    /**
     * Test attribute "hash_id_node"
     */
    public function testPropertyHashIdNode()
    {
    }

    /**
     * Test attribute "proof"
     */
    public function testPropertyProof()
    {
    }

    /**
     * Test attribute "anchors_complete"
     */
    public function testPropertyAnchorsComplete()
    {
    }
}
