<?php
/**
 * PostHashResponseMetaProcessingHintsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Chainpoint Node
 *
 * Documentation for the Chainpoint Node API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@chainpoint.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 1.0.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PostHashResponseMetaProcessingHintsTest Class Doc Comment
 *
 * @category    Class */
// * @description PostHashResponseMetaProcessingHints
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostHashResponseMetaProcessingHintsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PostHashResponseMetaProcessingHints"
     */
    public function testPostHashResponseMetaProcessingHints()
    {
    }

    /**
     * Test attribute "cal"
     */
    public function testPropertyCal()
    {
    }

    /**
     * Test attribute "eth"
     */
    public function testPropertyEth()
    {
    }

    /**
     * Test attribute "btc"
     */
    public function testPropertyBtc()
    {
    }
}
