<?php
/**
 * GetProofsResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Chainpoint\Client
 * @author   Chainpoint Codegen team
 * @link     https://github.com/Chainpoint-api/Chainpoint-codegen
 */

/**
 * Chainpoint Node
 *
 * Documentation for the Chainpoint Node API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@chainpoint.org
 * Generated by: https://github.com/Chainpoint-api/Chainpoint-codegen.git
 * Chainpoint Codegen version: 1.0.14
 */

/**
 * NOTE: This class is auto generated by the Chainpoint code generator program.
 * https://github.com/Chainpoint-api/Chainpoint-codegen
 * Do not edit the class manually.
 */

namespace Chainpoint\Client\Model;

use \ArrayAccess;
use \Chainpoint\Client\ObjectSerializer;

/**
 * GetProofsResponse Class Doc Comment
 *
 * @category Class
 * @package     Chainpoint\Client
 * @author      Chainpoint Codegen team
 * @link        https://github.com/Chainpoint-api/Chainpoint-codegen
 */
class GetProofsResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $ChainpointModelName = 'GetProofsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $ChainpointTypes = [
        'hash_id_node' => 'string',
        'proof' => 'object',
        'anchors_complete' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $ChainpointFormats = [
        'hash_id_node' => null,
        'proof' => null,
        'anchors_complete' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function ChainpointTypes()
    {
        return self::$ChainpointTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function ChainpointFormats()
    {
        return self::$ChainpointFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'hash_id_node' => 'hash_id_node',
        'proof' => 'proof',
        'anchors_complete' => 'anchors_complete'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'hash_id_node' => 'setHashIdNode',
        'proof' => 'setProof',
        'anchors_complete' => 'setAnchorsComplete'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'hash_id_node' => 'getHashIdNode',
        'proof' => 'getProof',
        'anchors_complete' => 'getAnchorsComplete'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$ChainpointModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['hash_id_node'] = isset($data['hash_id_node']) ? $data['hash_id_node'] : null;
        $this->container['proof'] = isset($data['proof']) ? $data['proof'] : null;
        $this->container['anchors_complete'] = isset($data['anchors_complete']) ? $data['anchors_complete'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets hash_id_node
     *
     * @return string
     */
    public function getHashIdNode()
    {
        return $this->container['hash_id_node'];
    }

    /**
     * Sets hash_id_node
     *
     * @param string $hash_id_node hash_id_node
     *
     * @return $this
     */
    public function setHashIdNode($hash_id_node)
    {
        $this->container['hash_id_node'] = $hash_id_node;

        return $this;
    }

    /**
     * Gets proof
     *
     * @return object
     */
    public function getProof()
    {
        return $this->container['proof'];
    }

    /**
     * Sets proof
     *
     * @param object $proof proof
     *
     * @return $this
     */
    public function setProof($proof)
    {
        $this->container['proof'] = $proof;

        return $this;
    }

    /**
     * Gets anchors_complete
     *
     * @return string[]
     */
    public function getAnchorsComplete()
    {
        return $this->container['anchors_complete'];
    }

    /**
     * Sets anchors_complete
     *
     * @param string[] $anchors_complete anchors_complete
     *
     * @return $this
     */
    public function setAnchorsComplete($anchors_complete)
    {
        $this->container['anchors_complete'] = $anchors_complete;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
