<?php
/**
 * CalendarApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Chainpoint\Client
 * @author   Chainpoint Codegen team
 * @link     https://github.com/Chainpoint-api/Chainpoint-codegen
 */

/**
 * Chainpoint Node
 *
 * Documentation for the Chainpoint Node API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@chainpoint.org
 * Generated by: https://github.com/Chainpoint-api/Chainpoint-codegen.git
 * Chainpoint Codegen version: 1.0.14
 */

/**
 * NOTE: This class is auto generated by the Chainpoint code generator program.
 * https://github.com/Chainpoint-api/Chainpoint-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Chainpoint\Client;

use \Chainpoint\Client\Configuration;
use \Chainpoint\Client\ApiException;
use \Chainpoint\Client\ObjectSerializer;

/**
 * CalendarApiTest Class Doc Comment
 *
 * @category Class
 * @package  Chainpoint\Client
 * @author   Chainpoint Codegen team
 * @link     https://github.com/Chainpoint-api/Chainpoint-codegen
 */
class CalendarApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for calendarHeightDataGet
     *
     * Retrieves the calendar block data_val at the given height.
     *
     */
    public function testCalendarHeightDataGet()
    {
    }

    /**
     * Test case for calendarHeightGet
     *
     * Retrieves the calendar block at the given height.
     *
     */
    public function testCalendarHeightGet()
    {
    }

    /**
     * Test case for calendarHeightHashGet
     *
     * Retrieves the calendar block hash at the given height.
     *
     */
    public function testCalendarHeightHashGet()
    {
    }
}
