<?php
/**
 * PostVerifyResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Chainpoint Node
 *
 * Documentation for the Chainpoint Node API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@chainpoint.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 1.0.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PostVerifyResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description PostVerifyResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostVerifyResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PostVerifyResponse"
     */
    public function testPostVerifyResponse()
    {
    }

    /**
     * Test attribute "proof_index"
     */
    public function testPropertyProofIndex()
    {
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }

    /**
     * Test attribute "hash_id_node"
     */
    public function testPropertyHashIdNode()
    {
    }

    /**
     * Test attribute "hash_submitted_node_at"
     */
    public function testPropertyHashSubmittedNodeAt()
    {
    }

    /**
     * Test attribute "hash_id_core"
     */
    public function testPropertyHashIdCore()
    {
    }

    /**
     * Test attribute "hash_submitted_core_at"
     */
    public function testPropertyHashSubmittedCoreAt()
    {
    }

    /**
     * Test attribute "anchors"
     */
    public function testPropertyAnchors()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
